### PR TITLE
Adding Topology Diagram

### PR DESCRIPTION
**Pull request by stevenhartley**
The following commit adds the topology drawio diagram found in the roadmap document.

### CODE REVIEW

**Review by PLeVasseur — APPROVED** [review]
:+1:

**Review by sophokles73 — COMMENTED** [review]
FMPOV it would be even better to add this as an SVG that has the diagram's xml embedded. This can be created from with in draw.io by means of exporting the diagram as SVG and then ticking the _embed copy of diagram_ checkbox.

**Comment by stevenhartley** [comment]
@sophokles73 done.

**Review by sophokles73 — APPROVED** [review]
LGTM

**Pull request merged**
